name: VPDC-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.21.2
  - pandas=1.3.3
  - matplotlib=3.4.3
  - dask=2021.9.1
  - rasterio=1.2.6
  - plotly=5.3.1
  - ipyleaflet=0.14.0
  - ipywidgets=7.6.5

